import {createServer} from 'node:http';
import {Pool} from 'pg';
import {loadSchoolConfig} from './config/env.js';
import {SessionCrypto} from './modules/school/session.crypto.js';
import {SchoolSessionRepository} from './modules/school/session.repository.js';
import {SchoolLoginService} from './modules/school/login.service.js';
import {LocalOcr} from './modules/school/ocr.provider.js';
import {SchoolService} from './modules/school/school.service.js';
import {SchoolController} from './modules/school/school.controller.js';
import {schoolRouter} from './modules/school/school.router.js';
const config=loadSchoolConfig();
const pool=new Pool({connectionString:config.SCHOOL_DATABASE_URL,max:5,connectionTimeoutMillis:3000,statement_timeout:5000});
pool.on('error',()=>console.error('School database unavailable'));
const sessions=new SchoolSessionRepository(pool,new SessionCrypto(config.SCHOOL_SESSION_KEY,config.SCHOOL_ACCOUNT_HASH_KEY));
const ocr=new LocalOcr(),service=new SchoolService(sessions,new SchoolLoginService((image,signal)=>ocr.recognize(image,signal)));
const server=createServer(schoolRouter(new SchoolController(service),config.SCHOOL_SERVICE_TOKEN));
server.requestTimeout=35000;server.headersTimeout=10000;
const cleanup=setInterval(()=>void sessions.cleanup().catch(()=>console.error('School session cleanup unavailable')),60000);cleanup.unref();
server.listen(config.SCHOOL_PORT,config.SCHOOL_HOST,()=>console.log('School adapter ready'));
for(const signal of ['SIGTERM','SIGINT'])process.once(signal,()=>{clearInterval(cleanup);server.close(()=>void pool.end());});
