export const SCHOOL_ERROR_STATUS:Record<string,number>={
 SCHOOL_IDENTITY_DENIED:403,SCHOOL_LOGIN_REQUIRED:401,SCHOOL_SESSION_EXPIRED:401,SCHOOL_SESSION_INVALID:401,
 SCHOOL_LOGIN_BUSY:409,SCHOOL_ACCOUNT_ALREADY_BOUND:409,SCHOOL_LOGIN_CANCELLED:409,SCHOOL_LOGIN_RATE_LIMIT:429,
 SCHOOL_CREDENTIALS_REJECTED:401,SCHOOL_AUTHENTICATION_REJECTED:401,SCHOOL_ACCOUNT_LOCKED:423,SCHOOL_CAPTCHA_FAILED:422,
 JSON_REQUIRED:415,REQUEST_TOO_LARGE:413,
};
